name: Build Docker Image
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/your-username/your-repo-name:latest
          cache-from: type=registry,ref=ghcr.io/your-username/your-repo-name:cache
          cache-to: type=registry,ref=ghcr.io/your-username/your-repo-name:cache,mode=max